export const routePaths = {
    home: '/',
    info: '/aktualne-info',
    history : '/historia-klubu',
    trainings : '/treningy',
    trainings_group1 : '/treningy/skupina_1',
    trainings_group2 : '/treningy/skupina_2',
    trainings_parkour1 : '/treningy/parkour_1',
    trainings_parkour2 : '/treningy/parkour_2',
    trainings_public : '/treningy/public',
    trainings_individual : '/treningy/individual',
    trainers : '/nasi-treneri',
    trainerDetail: '/nasi-treneri/:id',
    gallery : '/fotogaleria',
    contests : '/sutaze',
    contacts : '/kontakty',
}
